# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('place_name', models.CharField(max_length=50)),
                ('admin_name1', models.CharField(max_length=50)),
                ('admin_name2', models.CharField(max_length=50)),
                ('admin_name3', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.IntegerField()),
                ('malaria_cause', models.IntegerField()),
                ('malaria_deaths', models.IntegerField()),
                ('malnutrition_cause', models.IntegerField()),
                ('malnutrition_deaths', models.IntegerField()),
                ('tuberculosis_cause', models.IntegerField()),
                ('tuberculosis_deaths', models.IntegerField()),
                ('population', models.IntegerField()),
                ('malaria_risk_factor', models.FloatField()),
                ('malnutrition_risk_factor', models.FloatField()),
                ('tuberculosis_risk_factor', models.FloatField()),
                ('malaria_risk_index', models.FloatField()),
                ('malnutrition_risk_index', models.FloatField()),
                ('tuberculosis_risk_index', models.FloatField()),
            ],
        ),
    ]
