# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190426_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='place_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
