# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20190427_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
